### ISSUE TITLE
Horizontal Rule not getting printed correctly

### ISSUE THREAD

**Issue by madVis** [NielsLeenheer/ReceiptPrinterEncoder#14]
I'm trying to print horizontal rule but instead it's printing some other special characters. I've tried printing both 'single' and 'double' style.

```
encoder.initialize()
.rule({ style: 'double' })
        .line("Hello World!")
        .rule({ style: 'single' })
        .encode()
```

![IMG_0424](https://github.com/user-attachments/assets/66a85ca2-3416-46d7-9dda-beff914669fa)

**Comment by NielsLeenheer** [comment]
Oh, btw, the upcoming release will turn off double byte mode when you initialise the printer. So it will always be in the correct mode for the code pages.

**Comment by madVis** [comment]
Thanks for the clarification! I understand the behavior now. However, I have a follow-up question:

For any code page like GB18030 (say for Chinese, Korean etc), will the printer automatically switch to double-byte mode when necessary (i.e., enable Kanji mode)? If not, do I need to manually turn double-byte mode on before printing Chinese characters?

Also, if I print lines or characters using CP437 after printing Chinese text, would I need to switch back to single-byte mode, or does it handle that automatically?

Thanks again for your help!

**Comment by NielsLeenheer** [comment]
Right now this library does not have proper double byte support. Mainly because I personally haven't had the need to look into it, and adding it would increase the size of the library by.... a lot. The tables needed for this are huge. 

But it is on the list. Probably as some sort of optional dependency.

**Comment by madVis** [comment]
@NielsLeenheer I've got a few doubts regarding double-byte mode and codepages. It would be really helpful if you could clarify the following:

- When you mentioned that "this library does not have proper double byte support," does that mean we cannot use codepages for Chinese, Korean, Thai, etc.?
- If I want to support any of these codepages (which require double-byte mode) using .codepage('GB18030'), do I need to manually enable double-byte mode using raw commands?
- Additionally, if I want to print horizontal lines along with Chinese text, what’s the recommended approach? For example, would I need to switch between single-byte and double-byte mode for printing lines, or would using .codepage('auto') handle this automatically?

Thanks in advance for your help!

**Comment by NielsLeenheer** [comment]
First of all, double byte encoding is different from codepages. Chinese, Japanese and Korean use double byte encoding, while western languages and also Hebrew, Arabic and Thai use codepages. 

This library does not support double byte encoding. 

But it is possible to switch to double byte mode, encode it yourself  and switch back, and add the bytes required for that using the `raw()` command. You do need to switch back every time you want to use a function from the library, such as lines, because the library expects to be in single byte mode. Also using double byte mode in boxes and tables will cause issues, because double byte characters are wider than single byte characters, so the alignment will be off.

So not ideal.
